services:
  - type: web
    name: jwt-token-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    envVars:
      - key: CLIENT_EMAIL
        sync: false
      - key: PRIVATE_KEY
        sync: false
      - key: TOKEN_URI
        sync: false
